# -*- coding: utf-8 -*-
"""KerasCDSEB24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZrUyFBUhEB8NRlWB2MXZK3cjV_kJgiUN
"""

#Model Subclassing
import tensorflow as tf
from keras.layers import Dense,Input
class Mymodel(tf.keras.Model):
  def __init__(self):
    super(Mymodel,self).__init__()
    self.dense1 = Dense(8,activation = 'relu')
    self.dense2 = Dense(8,activation = 'relu')
    self.dense3 = Dense(1,activation = 'sigmoid')
  def call(self,inputs):
    xm = self.dense1(inputs)
    xm = self.dense2(xm)
    return self.dense3(xm)

